package catalogue

// Code generated by dev catalogue command DO NOT EDIT

import (
	citronasanateam "github.com/watermint/toolbox/citron/asana/team"
	citronasanateamproject "github.com/watermint/toolbox/citron/asana/team/project"
	citronasanateamtask "github.com/watermint/toolbox/citron/asana/team/task"
	citronasanaworkspace "github.com/watermint/toolbox/citron/asana/workspace"
	citronasanaworkspaceproject "github.com/watermint/toolbox/citron/asana/workspace/project"
	citrondeepltranslate "github.com/watermint/toolbox/citron/deepl/translate"
	citrondropboxfile "github.com/watermint/toolbox/citron/dropbox/file"
	citrondropboxfileaccount "github.com/watermint/toolbox/citron/dropbox/file/account"
	citrondropboxfilecompare "github.com/watermint/toolbox/citron/dropbox/file/compare"
	citrondropboxfileexport "github.com/watermint/toolbox/citron/dropbox/file/export"
	citrondropboxfileimport "github.com/watermint/toolbox/citron/dropbox/file/import"
	citrondropboxfileimportbatch "github.com/watermint/toolbox/citron/dropbox/file/import/batch"
	citrondropboxfilelock "github.com/watermint/toolbox/citron/dropbox/file/lock"
	citrondropboxfilelockall "github.com/watermint/toolbox/citron/dropbox/file/lock/all"
	citrondropboxfilelockbatch "github.com/watermint/toolbox/citron/dropbox/file/lock/batch"
	citrondropboxfilerequest "github.com/watermint/toolbox/citron/dropbox/file/request"
	citrondropboxfilerequestdelete "github.com/watermint/toolbox/citron/dropbox/file/request/delete"
	citrondropboxfilerestore "github.com/watermint/toolbox/citron/dropbox/file/restore"
	citrondropboxfilerevision "github.com/watermint/toolbox/citron/dropbox/file/revision"
	citrondropboxfilesearch "github.com/watermint/toolbox/citron/dropbox/file/search"
	citrondropboxfileshare "github.com/watermint/toolbox/citron/dropbox/file/share"
	citrondropboxfilesync "github.com/watermint/toolbox/citron/dropbox/file/sync"
	citrondropboxfiletag "github.com/watermint/toolbox/citron/dropbox/file/tag"
	citrondropboxfiletemplate "github.com/watermint/toolbox/citron/dropbox/file/template"
	citrondropboxpaper "github.com/watermint/toolbox/citron/dropbox/paper"
	citrondropboxsignaccount "github.com/watermint/toolbox/citron/dropbox/sign/account"
	citrondropboxteambackupdevice "github.com/watermint/toolbox/citron/dropbox/team/backup/device"
	citrondropboxteamgroup "github.com/watermint/toolbox/citron/dropbox/team/group"
	citrondropboxteamgroupbatch "github.com/watermint/toolbox/citron/dropbox/team/group/batch"
	citrondropboxteamgroupclear "github.com/watermint/toolbox/citron/dropbox/team/group/clear"
	citrondropboxteamgroupfolder "github.com/watermint/toolbox/citron/dropbox/team/group/folder"
	citrondropboxteamgroupmember "github.com/watermint/toolbox/citron/dropbox/team/group/member"
	citrondropboxteamgroupmemberbatch "github.com/watermint/toolbox/citron/dropbox/team/group/member/batch"
	citrondropboxteamgroupupdate "github.com/watermint/toolbox/citron/dropbox/team/group/update"
	citrondropboxteaminsight "github.com/watermint/toolbox/citron/dropbox/team/insight"
	citrondropboxteaminsightreport "github.com/watermint/toolbox/citron/dropbox/team/insight/report"
	citronfigmaaccount "github.com/watermint/toolbox/citron/figma/account"
	citronfigmafile "github.com/watermint/toolbox/citron/figma/file"
	citronfigmafileexport "github.com/watermint/toolbox/citron/figma/file/export"
	citronfigmafileexportall "github.com/watermint/toolbox/citron/figma/file/export/all"
	citronfigmaproject "github.com/watermint/toolbox/citron/figma/project"
	citrongithub "github.com/watermint/toolbox/citron/github"
	citrongithubcontent "github.com/watermint/toolbox/citron/github/content"
	citrongithubissue "github.com/watermint/toolbox/citron/github/issue"
	citrongithubrelease "github.com/watermint/toolbox/citron/github/release"
	citrongithubreleaseasset "github.com/watermint/toolbox/citron/github/release/asset"
	citrongithubtag "github.com/watermint/toolbox/citron/github/tag"
	citrongooglecalendarevent "github.com/watermint/toolbox/citron/google/calendar/event"
	citrongooglemailfilter "github.com/watermint/toolbox/citron/google/mail/filter"
	citrongooglemailfilterbatch "github.com/watermint/toolbox/citron/google/mail/filter/batch"
	citrongooglemaillabel "github.com/watermint/toolbox/citron/google/mail/label"
	citrongooglemailmessage "github.com/watermint/toolbox/citron/google/mail/message"
	citrongooglemailmessagelabel "github.com/watermint/toolbox/citron/google/mail/message/label"
	citrongooglemailmessageprocessed "github.com/watermint/toolbox/citron/google/mail/message/processed"
	citrongooglemailsendas "github.com/watermint/toolbox/citron/google/mail/sendas"
	citrongooglemailthread "github.com/watermint/toolbox/citron/google/mail/thread"
	citrongooglesheetssheet "github.com/watermint/toolbox/citron/google/sheets/sheet"
	citrongooglesheetsspreadsheet "github.com/watermint/toolbox/citron/google/sheets/spreadsheet"
	citrongoogletranslate "github.com/watermint/toolbox/citron/google/translate"
	citronlocalfiletemplate "github.com/watermint/toolbox/citron/local/file/template"
	citronslackconversation "github.com/watermint/toolbox/citron/slack/conversation"
	infra_recipe_rc_recipe "github.com/watermint/toolbox/infra/recipe/rc_recipe"
)

func AutoDetectedRecipesCitron() []infra_recipe_rc_recipe.Recipe {
	return []infra_recipe_rc_recipe.Recipe{
		&citronasanateam.List{},
		&citronasanateamproject.List{},
		&citronasanateamtask.List{},
		&citronasanaworkspace.List{},
		&citronasanaworkspaceproject.List{},
		&citrondeepltranslate.Text{},
		&citrondropboxfile.Copy{},
		&citrondropboxfile.Delete{},
		&citrondropboxfile.Info{},
		&citrondropboxfile.List{},
		&citrondropboxfile.Merge{},
		&citrondropboxfile.Move{},
		&citrondropboxfile.Replication{},
		&citrondropboxfile.Size{},
		&citrondropboxfile.Watch{},
		&citrondropboxfileaccount.Feature{},
		&citrondropboxfileaccount.Filesystem{},
		&citrondropboxfileaccount.Info{},
		&citrondropboxfilecompare.Account{},
		&citrondropboxfilecompare.Local{},
		&citrondropboxfileexport.Doc{},
		&citrondropboxfileexport.Url{},
		&citrondropboxfileimport.Url{},
		&citrondropboxfileimportbatch.Url{},
		&citrondropboxfilelock.Acquire{},
		&citrondropboxfilelock.List{},
		&citrondropboxfilelock.Release{},
		&citrondropboxfilelockall.Release{},
		&citrondropboxfilelockbatch.Acquire{},
		&citrondropboxfilelockbatch.Release{},
		&citrondropboxfilerequest.Create{},
		&citrondropboxfilerequest.List{},
		&citrondropboxfilerequestdelete.Closed{},
		&citrondropboxfilerequestdelete.Url{},
		&citrondropboxfilerestore.All{},
		&citrondropboxfilerevision.Download{},
		&citrondropboxfilerevision.List{},
		&citrondropboxfilerevision.Restore{},
		&citrondropboxfilesearch.Content{},
		&citrondropboxfilesearch.Name{},
		&citrondropboxfileshare.Info{},
		&citrondropboxfilesync.Down{},
		&citrondropboxfilesync.Online{},
		&citrondropboxfilesync.Up{},
		&citrondropboxfiletag.Add{},
		&citrondropboxfiletag.Delete{},
		&citrondropboxfiletag.List{},
		&citrondropboxfiletemplate.Apply{},
		&citrondropboxfiletemplate.Capture{},
		&citrondropboxpaper.Append{},
		&citrondropboxpaper.Create{},
		&citrondropboxpaper.Overwrite{},
		&citrondropboxpaper.Prepend{},
		&citrondropboxsignaccount.Info{},
		&citrondropboxteambackupdevice.Status{},
		&citrondropboxteamgroup.Add{},
		&citrondropboxteamgroup.Delete{},
		&citrondropboxteamgroup.List{},
		&citrondropboxteamgroup.Rename{},
		&citrondropboxteamgroupbatch.Add{},
		&citrondropboxteamgroupbatch.Delete{},
		&citrondropboxteamgroupclear.Externalid{},
		&citrondropboxteamgroupfolder.List{},
		&citrondropboxteamgroupmember.Add{},
		&citrondropboxteamgroupmember.Delete{},
		&citrondropboxteamgroupmember.List{},
		&citrondropboxteamgroupmemberbatch.Add{},
		&citrondropboxteamgroupmemberbatch.Delete{},
		&citrondropboxteamgroupmemberbatch.Update{},
		&citrondropboxteamgroupupdate.Type{},
		&citrondropboxteaminsight.Scan{},
		&citrondropboxteaminsight.Scanretry{},
		&citrondropboxteaminsight.Summarize{},
		&citrondropboxteaminsightreport.Teamfoldermember{},
		&citronfigmaaccount.Info{},
		&citronfigmafile.Info{},
		&citronfigmafile.List{},
		&citronfigmafileexport.Frame{},
		&citronfigmafileexport.Node{},
		&citronfigmafileexport.Page{},
		&citronfigmafileexportall.Page{},
		&citronfigmaproject.List{},
		&citrongithub.Profile{},
		&citrongithubcontent.Get{},
		&citrongithubcontent.Put{},
		&citrongithubissue.List{},
		&citrongithubrelease.Draft{},
		&citrongithubrelease.List{},
		&citrongithubreleaseasset.Download{},
		&citrongithubreleaseasset.List{},
		&citrongithubreleaseasset.Upload{},
		&citrongithubtag.Create{},
		&citrongooglecalendarevent.List{},
		&citrongooglemailfilter.Add{},
		&citrongooglemailfilter.Delete{},
		&citrongooglemailfilter.List{},
		&citrongooglemailfilterbatch.Add{},
		&citrongooglemaillabel.Add{},
		&citrongooglemaillabel.Delete{},
		&citrongooglemaillabel.List{},
		&citrongooglemaillabel.Rename{},
		&citrongooglemailmessage.List{},
		&citrongooglemailmessage.Send{},
		&citrongooglemailmessagelabel.Add{},
		&citrongooglemailmessagelabel.Delete{},
		&citrongooglemailmessageprocessed.List{},
		&citrongooglemailsendas.Add{},
		&citrongooglemailsendas.Delete{},
		&citrongooglemailsendas.List{},
		&citrongooglemailthread.List{},
		&citrongooglesheetssheet.Append{},
		&citrongooglesheetssheet.Clear{},
		&citrongooglesheetssheet.Create{},
		&citrongooglesheetssheet.Delete{},
		&citrongooglesheetssheet.Export{},
		&citrongooglesheetssheet.Import{},
		&citrongooglesheetssheet.List{},
		&citrongooglesheetsspreadsheet.Create{},
		&citrongoogletranslate.Text{},
		&citronlocalfiletemplate.Apply{},
		&citronlocalfiletemplate.Capture{},
		&citronslackconversation.History{},
		&citronslackconversation.List{},
	}
}
