package catalogue

// Code generated by dev catalogue command DO NOT EDIT

import (
	infraapiapi_auth_impl "github.com/watermint/toolbox/infra/api/api_auth_impl"
	"github.com/watermint/toolbox/infra/control/app_feature"
	ingredientbootstrap "github.com/watermint/toolbox/ingredient/bootstrap"
)

func AutoDetectedFeatures() []app_feature.OptIn {
	return []app_feature.OptIn{
		&infraapiapi_auth_impl.OptInFeatureRedirect{},
		&ingredientbootstrap.OptInFeatureAutodelete{},
	}
}
