package catalogue

// Code generated by dev catalogue command DO NOT EDIT

import (
	infra_recipe_rc_recipe "github.com/watermint/toolbox/infra/recipe/rc_recipe"
	ingredientbootstrap "github.com/watermint/toolbox/ingredient/ig_bootstrap"
	ingredientfile "github.com/watermint/toolbox/ingredient/ig_dropbox/ig_file"
	"github.com/watermint/toolbox/ingredient/ig_dropbox/ig_team/ig_namespace/ig_file"
	ingredientteamfolder "github.com/watermint/toolbox/ingredient/ig_dropbox/ig_teamfolder"
	ingredientjob "github.com/watermint/toolbox/ingredient/ig_job"
)

func AutoDetectedIngredients() []infra_recipe_rc_recipe.Recipe {
	return []infra_recipe_rc_recipe.Recipe{
		&ingredientbootstrap.Autodelete{},
		&ingredientbootstrap.Bootstrap{},
		&ingredientfile.Upload{},
		&ingredientjob.Delete{},
		&ig_file.List{},
		&ig_file.Size{},
		&ingredientteamfolder.Replication{},
	}
}
