package catalogue

// Code generated by dev catalogue command DO NOT EDIT

import (
	infra_recipe_rc_recipe "github.com/watermint/toolbox/infra/recipe/rc_recipe"
	ingredientbootstrap "github.com/watermint/toolbox/ingredient/ig_bootstrap"
	ingredientfile "github.com/watermint/toolbox/ingredient/ig_file"
	ingredientjob "github.com/watermint/toolbox/ingredient/ig_job"
	ingredientteamnamespacefile "github.com/watermint/toolbox/ingredient/ig_team/ig_namespace/ig_file"
	ingredientteamfolder "github.com/watermint/toolbox/ingredient/ig_teamfolder"
)

func AutoDetectedIngredients() []infra_recipe_rc_recipe.Recipe {
	return []infra_recipe_rc_recipe.Recipe{
		&ingredientbootstrap.Autodelete{},
		&ingredientbootstrap.Bootstrap{},
		&ingredientfile.Upload{},
		&ingredientjob.Delete{},
		&ingredientteamnamespacefile.List{},
		&ingredientteamnamespacefile.Size{},
		&ingredientteamfolder.Replication{},
	}
}
