package catalogue

// Code generated by dev catalogue command DO NOT EDIT

import (
	infra_recipe_rc_recipe "github.com/watermint/toolbox/infra/recipe/rc_recipe"
)

func AutoDetectedRecipesLime() []infra_recipe_rc_recipe.Recipe {
	return []infra_recipe_rc_recipe.Recipe{}
}
